### ISSUE TITLE
Hello and thx for this module , but i have a prob ... 

### ISSUE THREAD

**Issue by Egalistel** [Smiche/MMM-DiscordWatch#1]
hello, I don't know if this is normal, but when a message arrives, it is displayed 4 times in a row on the mirror.
in any case it's perfect, I was just looking for a bot for my discord :) and is it possible to launch the bot script automatically when launching the raspberry? Thanks again
![Capture d’écran 2021-02-14 232430](https://user-images.githubusercontent.com/61868339/107890948-12cb1a80-6f1c-11eb-9e86-c9989eb4db9f.png)

**Comment by Smiche** [comment]
Hello, the module is quite new and I made it in just a day, so all the bugs are not yet flushed out.

And that isn't normal behavior, can you let me know how this happened so I can try to reproduce it?

The bot will connect as soon as magic mirror is opened. Also make sure you don't use the token for any other bot as if 2 bots try to use the same token it will cause drops/reconnects.

**Comment by Egalistel** [comment]
hello and thank you for the answer, I had never created a bot before, so I followed the procedure with the discord.js file for the creation of this one (the bot is launched on the rapsberry which contains the magic mirror ), I then simply copied and pasted the part of the modules in the mirror config by adding the token received during the creation

**Comment by Smiche** [comment]
You don't need to run a discord.js bot alongside this, there is already built-in bot code for this. So if you're using the token both with magicmirror and another bot that will make it reconnect a lot. Simply have only magicmirror running and nothing else.

**Comment by Egalistel** [comment]
ok so here is my mistake, a big thank you, it actually works much better, again bravo for modifying, it will give me a lot of service :)

**Comment by Smiche** [comment]
If you're interested in some new features let me know.

I can also add more instructions to let people know that nothing external is needed.

Also when it reconnects it loads same message twice, so that's definitely a bug that I'll fix (e.g. wifi lost, then it reconnects it might double messages)
